use_frameworks!

platform :ios, '8.0'

target 'XAbstractionLibrary-Base_Example' do
  pod 'XAbstractionLibrary-Base', :path => '../'
  
  target 'XAbstractionLibrary-Base_Tests' do
    inherit! :search_paths


  end
end
